use stocks;

CREATE TABLE IF NOT EXISTS `users`(

    id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    api_key UUID UNIQUE NOT NULL DEFAULT UUID(),
    `password` VARCHAR(255) NOT NULL
);